# Generated by Django 5.1.6 on 2025-02-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_aitool_likes_aitool_shares_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
