# Generated by Django 5.1.6 on 2025-02-12 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0004_remove_bookmark_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='aitool',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
