# Generated by Django 5.1.6 on 2025-02-18 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0005_aitool_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aitool',
            name='paid',
            field=models.CharField(choices=[('Free', 'Free'), ('Freemium', 'Freemium'), ('Premium', 'Premium')], default='Free', max_length=10),
        ),
    ]
